action_time: 0.01
alg: SAC
bullet_time_step: 0.0002
checkpoint_cb:
  save_freq: 2000
env_id: InHandManipulationInverted-v0
eval_cb:
  eval_freq: 2000
  n_eval_episodes: 1
failure_penalty_multiplier: 100
max_episode_steps: 100
max_torque_rate: 130
num_threads: 1
observation_flags:
  box_pos:
  box_or:
  box_velocity:
  positions: 4
  velocities: 4
  tip_pos:
  angles: 4
  curvatures: 5
  applied_input_torques:
policy: SACMlpPolicy
reward_flags:
  z_rotation_step: 1000
  x_rotation: -1
  y_rotation: -1
  position: -1
seed: 15
torque_multiplier: 65
training_timesteps: 500000
policy_kwargs: {'learning_rate': 0.0003, 'buffer_size': 500000, 'learning_starts': 50, 'batch_size': 25}
invert_hand: True
tensorboard_log: /home/lanpei/thesis_project/somo-rl/test_exp/InHandManipulationInverted-v0/SAC/random_seed_15/tensorboard_log
